-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.job_seekers
(
    user_id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    nationality_id character varying(11) NOT NULL UNIQUE,
    date_of_birth date NOT NULL,
    gender character varying NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying NOT NULL UNIQUE,
    password character varying(16) NOT NULL,
    is_active boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying NOT NULL,
    web_site character varying NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.system_employees
(
    user_id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    nationality_id character varying(11) NOT NULL UNIQUE,
    date_of_birth date NOT NULL,
    gender character varying NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employee_positions
(
    id integer NOT NULL,
    position_name character varying NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE public.phone_numbers
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    country_code character varying NOT NULL,
    phone_number character varying NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_employees
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.phone_numbers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


END;